/**
 * @mineproj/create-plugin — scaffold a mineproj plugin package
 *
 * Usage:
 *   npx create-plugin <plugin-name>
 *
 * Creates a new directory with the plugin skeleton including:
 * - package.json with @mineproj/core dependency
 * - src/index.ts with all 10 hook examples
 * - vitest config
 * - TypeScript config
 */

import { writeFile, mkdir } from 'node:fs/promises';
import { join, resolve } from 'node:path';

const PLUGIN_TEMPLATE = `/**
 * {{name}} — a mineproj plugin
 *
 * Generated by create-plugin. Edit this file to implement your plugin logic.
 * See https://mineproj.dev/docs/plugin-development for the full API reference.
 */
import type { MineprojPlugin } from '@mineproj/core';

export interface {{pascalName}}Options {
  /** Enable verbose logging. */
  verbose?: boolean;
}

export function define{{pascalName}}Plugin(options: {{pascalName}}Options = {}): MineprojPlugin {
  return {
    name: '{{name}}',
    hooks: {
      // Called after config is resolved (waterfall, can modify config)
      'config:resolved': async (config) => {
        if (options.verbose) console.log('[{{name}}] config resolved');
        return config;
      },

      // Called after data is loaded (seq)
      'data:loaded': async () => {
        if (options.verbose) console.log('[{{name}}] data loaded');
      },

      // Called after data is validated (seq)
      'data:validated': async () => {
        if (options.verbose) console.log('[{{name}}] data validated');
      },

      // Called before asset processing (seq)
      'assets:process': async () => {
        if (options.verbose) console.log('[{{name}}] processing assets');
      },

      // Called during route collection (waterfall, can modify routes)
      'routes:collect': async (routes) => {
        if (options.verbose) console.log('[{{name}}] collected', routes.length, 'routes');
        return routes;
      },

      // Called before API endpoint generation (waterfall)
      'api:endpoints': async (endpoints) => {
        if (options.verbose) console.log('[{{name}}] generating endpoints');
        return endpoints;
      },

      // Called before each page render (waterfall, can modify HTML)
      'render:before': async (html, ctx) => {
        if (options.verbose) console.log('[{{name}}] rendering page');
        return html;
      },

      // Called during emit phase (seq, for writing additional files)
      'emit': async () => {
        if (options.verbose) console.log('[{{name}}] emitting files');
      },

      // Called after build completes (seq)
      'build:done': async () => {
        if (options.verbose) console.log('[{{name}}] build complete');
      },
    },
  };
};
`;

const PACKAGE_JSON = `{
  "name": "{{name}}",
  "version": "0.1.0",
  "description": "mineproj plugin: {{description}}",
  "license": "Apache-2.0",
  "type": "module",
  "main": "./src/index.ts",
  "exports": { ".": "./src/index.ts" },
  "scripts": {
    "test": "vitest run",
    "typecheck": "tsc --noEmit"
  },
  "dependencies": {
    "@mineproj/core": "^0.0.0"
  },
  "devDependencies": {
    "typescript": "^5.7.0",
    "vitest": "^4.0.0"
  }
}
`;

const VITEST_CONFIG = `import { defineConfig } from 'vitest/config';
export default defineConfig({ test: { environment: 'node' } });
`;

const TS_CONFIG = `{
  "compilerOptions": {
    "target": "ESNext",
    "module": "ESNext",
    "moduleResolution": "bundler",
    "strict": true,
    "declaration": true,
    "outDir": "dist",
    "rootDir": "src"
  },
  "include": ["src"]
}
`;

function toPascalCase(str: string): string {
  return str
    .replace(/[^a-zA-Z0-9]+/g, ' ')
    .split(' ')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join('');
}

function applyTemplate(template: string, name: string, description: string): string {
  return template
    .replace(/\{\{name\}\}/g, name)
    .replace(/\{\{pascalName\}\}/g, toPascalCase(name))
    .replace(/\{\{description\}\}/g, description);
}

export async function scaffoldPlugin(name: string, dir: string, description = 'A mineproj plugin'): Promise<void> {
  const pluginDir = resolve(dir, name);
  const srcDir = join(pluginDir, 'src');

  await mkdir(srcDir, { recursive: true });

  await writeFile(join(pluginDir, 'package.json'), applyTemplate(PACKAGE_JSON, name, description), 'utf-8');
  await writeFile(join(pluginDir, 'src', 'index.ts'), applyTemplate(PLUGIN_TEMPLATE, name, description), 'utf-8');
  await writeFile(join(pluginDir, 'vitest.config.ts'), VITEST_CONFIG, 'utf-8');
  await writeFile(join(pluginDir, 'tsconfig.json'), TS_CONFIG, 'utf-8');

  console.log(`Plugin "${name}" scaffolded at ${pluginDir}`);
  console.log(`  src/index.ts  — plugin implementation`);
  console.log(`  package.json  — package manifest`);
  console.log(`  vitest.config.ts — test configuration`);
  console.log(`  tsconfig.json — TypeScript configuration`);
}

// CLI entry point
const name = process.argv[2];
if (name) {
  const dir = process.argv[3] || process.cwd();
  const description = process.argv[4] || 'A mineproj plugin';
  scaffoldPlugin(name, dir, description).catch(console.error);
}