import { defineConfig } from 'vitepress'

const base = process.env.DOCS_BASE ?? '/mineproj/'

// Shared sidebar configuration used across all locales
const guideSidebar = (prefix: string) => [
  {
    text: 'Getting Started',
    items: [
      { text: 'Quick Start', link: `${prefix}guide/getting-started` },
      { text: 'Configuration', link: `${prefix}guide/configuration` },
      { text: 'Data Model', link: `${prefix}guide/data-model` },
      { text: 'Deploying', link: `${prefix}guide/deploying` },
    ],
  },
  {
    text: 'Theme Development',
    items: [
      { text: 'Theme Basics', link: `${prefix}guide/theme-development` },
      { text: 'Layouts & Slots', link: `${prefix}guide/theme-layouts` },
      { text: 'Islands', link: `${prefix}guide/theme-islands` },
    ],
  },
  {
    text: 'Plugin Development',
    items: [
      { text: 'Plugin Basics', link: `${prefix}guide/plugin-development` },
      { text: 'Lifecycle Hooks', link: `${prefix}guide/plugin-hooks` },
    ],
  },
  {
    text: 'Reference',
    items: [
      { text: 'API Reference', link: `${prefix}guide/api-reference` },
      { text: 'CLI Reference', link: `${prefix}guide/cli-reference` },
      { text: 'Configuration Reference', link: `${prefix}guide/configuration` },
    ],
  },
]

export default defineConfig({
  base,
  title: 'mineproj',
  description: 'Apache-2.0 licensed static site generator for personal project portfolios',
  lastUpdated: true,
  cleanUrls: true,
  appearance: 'toggle',
  markdown: {
    lineNumbers: true,
  },
  locales: {
    root: {
      label: 'English',
      lang: 'en',
      dir: 'ltr',
      title: 'mineproj',
      description: 'Apache-2.0 licensed static site generator for personal project portfolios',
      themeConfig: {
        nav: [
          { text: 'Guide', link: '/guide/getting-started' },
          { text: 'Theme Dev', link: '/guide/theme-development' },
          { text: 'Plugin Dev', link: '/guide/plugin-development' },
          { text: 'API', link: '/guide/api-reference' },
          { text: 'Deploy', link: '/guide/deploying' },
        ],
        sidebar: { '/': guideSidebar('/') },
        docFooter: { prev: 'Previous', next: 'Next' },
        outline: { label: 'On this page' },
        lastUpdated: { text: 'Last updated' },
        returnToTopLabel: 'Back to top',
        sidebarMenuLabel: 'Menu',
        darkModeSwitchLabel: 'Appearance',
        lightModeSwitchTitle: 'Switch to light mode',
        darkModeSwitchTitle: 'Switch to dark mode',
      },
    },
    'zh-CN': {
      label: '简体中文',
      lang: 'zh-CN',
      dir: 'ltr',
      title: 'mineproj',
      description: 'Apache-2.0 许可的静态站点生成器，用于个人项目展示',
      themeConfig: {
        nav: [
          { text: '指南', link: '/zh-CN/guide/getting-started' },
          { text: '主题开发', link: '/zh-CN/guide/theme-development' },
          { text: '插件开发', link: '/zh-CN/guide/plugin-development' },
          { text: 'API', link: '/zh-CN/guide/api-reference' },
          { text: '部署', link: '/zh-CN/guide/deploying' },
        ],
        sidebar: { '/zh-CN/': guideSidebar('/zh-CN/') },
        docFooter: { prev: '上一页', next: '下一页' },
        outline: { label: '本页目录' },
        lastUpdated: { text: '最后更新于' },
        returnToTopLabel: '回到顶部',
        sidebarMenuLabel: '菜单',
        darkModeSwitchLabel: '主题',
        lightModeSwitchTitle: '切换到浅色模式',
        darkModeSwitchTitle: '切换到深色模式',
      },
    },
    hi: {
      label: 'हिन्दी',
      lang: 'hi',
      dir: 'ltr',
      title: 'mineproj',
      description: 'Apache-2.0 लाइसेंस प्राप्त स्थैतिक साइट जनरेटर',
      themeConfig: {
        nav: [
          { text: 'गाइड', link: '/hi/guide/getting-started' },
          { text: 'थीम', link: '/hi/guide/theme-development' },
          { text: 'प्लगइन', link: '/hi/guide/plugin-development' },
          { text: 'API', link: '/hi/guide/api-reference' },
          { text: 'डिप्लॉय', link: '/hi/guide/deploying' },
        ],
        sidebar: { '/hi/': guideSidebar('/hi/') },
        docFooter: { prev: 'पिछला', next: 'अगला' },
        outline: { label: 'इस पेज पर' },
        lastUpdated: { text: 'अंतिम अपडेट' },
        returnToTopLabel: 'वापस ऊपर',
        sidebarMenuLabel: 'मेनू',
        darkModeSwitchLabel: 'दिखावट',
        lightModeSwitchTitle: 'हल्का मोड',
        darkModeSwitchTitle: 'गहरा मोड',
      },
    },
    es: {
      label: 'Español',
      lang: 'es',
      dir: 'ltr',
      title: 'mineproj',
      description: 'Generador de sitios estáticos con licencia Apache-2.0',
      themeConfig: {
        nav: [
          { text: 'Guía', link: '/es/guide/getting-started' },
          { text: 'Temas', link: '/es/guide/theme-development' },
          { text: 'Plugins', link: '/es/guide/plugin-development' },
          { text: 'API', link: '/es/guide/api-reference' },
          { text: 'Despliegue', link: '/es/guide/deploying' },
        ],
        sidebar: { '/es/': guideSidebar('/es/') },
        docFooter: { prev: 'Anterior', next: 'Siguiente' },
        outline: { label: 'En esta página' },
        lastUpdated: { text: 'Última actualización' },
        returnToTopLabel: 'Volver arriba',
        sidebarMenuLabel: 'Menú',
        darkModeSwitchLabel: 'Apariencia',
        lightModeSwitchTitle: 'Modo claro',
        darkModeSwitchTitle: 'Modo oscuro',
      },
    },
    ar: {
      label: 'العربية',
      lang: 'ar',
      dir: 'rtl',
      title: 'mineproj',
      description: 'مولد مواقع ثابتة مرخص بموجب Apache-2.0',
      themeConfig: {
        nav: [
          { text: 'دليل', link: '/ar/guide/getting-started' },
          { text: 'تطوير السمات', link: '/ar/guide/theme-development' },
          { text: 'تطوير الإضافات', link: '/ar/guide/plugin-development' },
          { text: 'API', link: '/ar/guide/api-reference' },
          { text: 'نشر', link: '/ar/guide/deploying' },
        ],
        sidebar: { '/ar/': guideSidebar('/ar/') },
        docFooter: { prev: 'السابق', next: 'التالي' },
        outline: { label: 'في هذه الصفحة' },
        lastUpdated: { text: 'آخر تحديث' },
        returnToTopLabel: 'العودة إلى الأعلى',
        sidebarMenuLabel: 'القائمة',
        darkModeSwitchLabel: 'المظهر',
        lightModeSwitchTitle: 'الوضع الفاتح',
        darkModeSwitchTitle: 'الوضع الداكن',
      },
    },
    fr: {
      label: 'Français',
      lang: 'fr',
      dir: 'ltr',
      title: 'mineproj',
      description: 'Générateur de sites statiques sous licence Apache-2.0',
      themeConfig: {
        nav: [
          { text: 'Guide', link: '/fr/guide/getting-started' },
          { text: 'Thèmes', link: '/fr/guide/theme-development' },
          { text: 'Plugins', link: '/fr/guide/plugin-development' },
          { text: 'API', link: '/fr/guide/api-reference' },
          { text: 'Déploiement', link: '/fr/guide/deploying' },
        ],
        sidebar: { '/fr/': guideSidebar('/fr/') },
        docFooter: { prev: 'Précédent', next: 'Suivant' },
        outline: { label: 'Sur cette page' },
        lastUpdated: { text: 'Dernière mise à jour' },
        returnToTopLabel: 'Retour en haut',
        sidebarMenuLabel: 'Menu',
        darkModeSwitchLabel: 'Apparence',
        lightModeSwitchTitle: 'Mode clair',
        darkModeSwitchTitle: 'Mode sombre',
      },
    },
    bn: {
      label: 'বাংলা',
      lang: 'bn',
      dir: 'ltr',
      title: 'mineproj',
      description: 'Apache-2.0 লাইসেন্সকৃত স্ট্যাটিক সাইট জেনারেটর',
      themeConfig: {
        nav: [
          { text: 'গাইড', link: '/bn/guide/getting-started' },
          { text: 'থিম', link: '/bn/guide/theme-development' },
          { text: 'প্লাগইন', link: '/bn/guide/plugin-development' },
          { text: 'API', link: '/bn/guide/api-reference' },
          { text: 'ডিপ্লয়', link: '/bn/guide/deploying' },
        ],
        sidebar: { '/bn/': guideSidebar('/bn/') },
        docFooter: { prev: 'পূর্ববর্তী', next: 'পরবর্তী' },
        outline: { label: 'এই পৃষ্ঠায়' },
        lastUpdated: { text: 'সর্বশেষ আপডেট' },
        returnToTopLabel: 'উপরে ফিরে যান',
        sidebarMenuLabel: 'মেনু',
        darkModeSwitchLabel: 'চেহারা',
        lightModeSwitchTitle: 'হালকা মোড',
        darkModeSwitchTitle: 'গাঢ় মোড',
      },
    },
    pt: {
      label: 'Português',
      lang: 'pt',
      dir: 'ltr',
      title: 'mineproj',
      description: 'Gerador de sites estáticos licenciado sob Apache-2.0',
      themeConfig: {
        nav: [
          { text: 'Guia', link: '/pt/guide/getting-started' },
          { text: 'Temas', link: '/pt/guide/theme-development' },
          { text: 'Plugins', link: '/pt/guide/plugin-development' },
          { text: 'API', link: '/pt/guide/api-reference' },
          { text: 'Implantar', link: '/pt/guide/deploying' },
        ],
        sidebar: { '/pt/': guideSidebar('/pt/') },
        docFooter: { prev: 'Anterior', next: 'Próximo' },
        outline: { label: 'Nesta página' },
        lastUpdated: { text: 'Última atualização' },
        returnToTopLabel: 'Voltar ao topo',
        sidebarMenuLabel: 'Menu',
        darkModeSwitchLabel: 'Aparência',
        lightModeSwitchTitle: 'Modo claro',
        darkModeSwitchTitle: 'Modo escuro',
      },
    },
    ru: {
      label: 'Русский',
      lang: 'ru',
      dir: 'ltr',
      title: 'mineproj',
      description: 'Генератор статических сайтов с лицензией Apache-2.0',
      themeConfig: {
        nav: [
          { text: 'Руководство', link: '/ru/guide/getting-started' },
          { text: 'Темы', link: '/ru/guide/theme-development' },
          { text: 'Плагины', link: '/ru/guide/plugin-development' },
          { text: 'API', link: '/ru/guide/api-reference' },
          { text: 'Развертывание', link: '/ru/guide/deploying' },
        ],
        sidebar: { '/ru/': guideSidebar('/ru/') },
        docFooter: { prev: 'Назад', next: 'Вперед' },
        outline: { label: 'На этой странице' },
        lastUpdated: { text: 'Последнее обновление' },
        returnToTopLabel: 'Наверх',
        sidebarMenuLabel: 'Меню',
        darkModeSwitchLabel: 'Вид',
        lightModeSwitchTitle: 'Светлый режим',
        darkModeSwitchTitle: 'Темный режим',
      },
    },
    id: {
      label: 'Bahasa Indonesia',
      lang: 'id',
      dir: 'ltr',
      title: 'mineproj',
      description: 'Pembangun situs statis berlisensi Apache-2.0',
      themeConfig: {
        nav: [
          { text: 'Panduan', link: '/id/guide/getting-started' },
          { text: 'Tema', link: '/id/guide/theme-development' },
          { text: 'Plugin', link: '/id/guide/plugin-development' },
          { text: 'API', link: '/id/guide/api-reference' },
          { text: 'Deploy', link: '/id/guide/deploying' },
        ],
        sidebar: { '/id/': guideSidebar('/id/') },
        docFooter: { prev: 'Sebelumnya', next: 'Selanjutnya' },
        outline: { label: 'Di halaman ini' },
        lastUpdated: { text: 'Terakhir diperbarui' },
        returnToTopLabel: 'Kembali ke atas',
        sidebarMenuLabel: 'Menu',
        darkModeSwitchLabel: 'Tampilan',
        lightModeSwitchTitle: 'Mode terang',
        darkModeSwitchTitle: 'Mode gelap',
      },
    },
    ko: {
      label: '한국어',
      lang: 'ko',
      dir: 'ltr',
      title: 'mineproj',
      description: 'Apache-2.0 라이선스 정적 사이트 생성기',
      themeConfig: {
        nav: [
          { text: '가이드', link: '/ko/guide/getting-started' },
          { text: '테마 개발', link: '/ko/guide/theme-development' },
          { text: '플러그인 개발', link: '/ko/guide/plugin-development' },
          { text: 'API', link: '/ko/guide/api-reference' },
          { text: '배포', link: '/ko/guide/deploying' },
        ],
        sidebar: { '/ko/': guideSidebar('/ko/') },
        docFooter: { prev: '이전', next: '다음' },
        outline: { label: '페이지 내용' },
        lastUpdated: { text: '마지막 업데이트' },
        returnToTopLabel: '맨 위로',
        sidebarMenuLabel: '메뉴',
        darkModeSwitchLabel: '테마',
        lightModeSwitchTitle: '라이트 모드',
        darkModeSwitchTitle: '다크 모드',
      },
    },
  },
  themeConfig: {
    socialLinks: [
      { icon: 'github', link: 'https://github.com/Maicarons/mineproj' },
    ],
    search: {
      provider: 'local',
    },
    footer: {
      message: 'Released under the Apache-2.0 License.',
      copyright: 'Copyright © 2026 mineproj contributors',
    },
    editLink: {
      pattern: 'https://github.com/Maicarons/mineproj/edit/main/docs/:path',
      text: 'Edit this page on GitHub',
    },
  },
})